name: run CodeStyle

on: [push]

jobs:
  run-phpunit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: composer install
        run: |
          sudo curl -s https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          ls -la
          composer install
        
     
  
